networks:
  saas-llm-chat-app:

services:
  db:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: llm-chat
    networks:
      - saas-llm-chat-app
    ports:
      - 5432:5432
  llm-chat:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/llm-chat
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
      APP_URL: http://localhost:4002
      SVIX_URL: ${SVIX_URL}
      SVIX_API_KEY: ${SVIX_API_KEY}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      RETRACED_URL: ${RETRACED_URL}
      RETRACED_API_KEY: ${RETRACED_API_KEY}
      RETRACED_PROJECT_ID: ${RETRACED_PROJECT_ID}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      TERMINUS_LLM_TENANT: _jackson_boxyhq
      TERMINUS_LLM_PRODUCT: llm-demo
      TERMINUS_WRITE_API_KEY: writeAPIKey1
      TERMINUS_READ_API_KEY: readAPIKey1
      TERMINUS_PROXY_HOST_URL: http://localhost:3002
      TERMINUS_ADMIN_ROOT_TOKEN: adminAPIKey1
    networks:
      - saas-llm-chat-app
    ports:
      - 4002:4002
    depends_on:
      - db
  db-migrate:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/llm-chat
    command: npm run db:migrate
    networks:
      - saas-llm-chat-app
    depends_on:
      - db
